# Change these first
owner: edoaurahman # Your GitHub organization or username, where this repository lives
repo: check-web-uptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Detik
    url: https://www.detik.com/
  - name: UUDUMP
    url: https://uupdump.net/
  - name: Gokuhost
    url: https://gokuhost.com/
  - name: Siakad Polinema
    url: http://siakad.polinema.ac.id/
  - name: Lms Polinema
    url: https://lmsslc.polinema.ac.id/
  - name: Lms Polinema
    url: https://serverjogja.xcodehoster.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /check-web-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
